-- CREATE USER_PAYMENT_CUSTOMER TABLE
CREATE TABLE IF NOT EXISTS USER_PAYMENT_CUSTOMER (
  ID VARCHAR(255) NOT NULL UNIQUE,
  USER_ID VARCHAR(255) NOT NULL UNIQUE,
  USER_NAME VARCHAR(255) NOT NULL UNIQUE,
  PAYMENT_CUSTOMER_ID  VARCHAR(255) NOT NULL UNIQUE,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (USER_ID)
);
CREATE UNIQUE INDEX USER_PAYMENT_CUSTOMER_USER_ID_INDEX ON USER_PAYMENT_CUSTOMER (USER_ID);
