-- CREATE CREDIT_CARD_ID TABLE
CREATE TABLE IF NOT EXISTS CREDIT_CARD (
	CREDIT_CARD_ID VARCHAR(255) NOT NULL,
	USER_ID VARCHAR(255) NOT NULL,
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255),
	CARD_NUMBER VARCHAR(255) NOT NULL,
	LAST_4_DIGITS VARCHAR(255),
	EXPIRATION_MONTH VARCHAR(255) NOT NULL,
	EXPIRATION_YEAR VARCHAR(255) NOT NULL,
	CVV VARCHAR(255) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (CREDIT_CARD_ID)
);
CREATE UNIQUE INDEX CREDIT_CARD_ID_INDEX ON CREDIT_CARD (CREDIT_CARD_ID);
