-- create billing address table
CREATE TABLE IF NOT EXISTS BILLING_ADDRESS (
    BILLING_ADDRESS_ID VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255),
    CITY VARCHAR(255),
    COUNTRY VARCHAR(255),
    STATE VARCHAR(255),
    ZIPCODE VARCHAR(255),
    PRIMARY KEY (BILLING_ADDRESS_ID)
);

-- create shipping address table
CREATE TABLE IF NOT EXISTS SHIPPING_ADDRESS (
    SHIPPING_ADDRESS_ID VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255),
    CITY VARCHAR(255),
    COUNTRY VARCHAR(255),
    STATE VARCHAR(255),
    ZIPCODE VARCHAR(255),
    PRIMARY KEY (SHIPPING_ADDRESS_ID)
);