-- create cart table
CREATE TABLE IF NOT EXISTS CART (
    CART_ID VARCHAR(255) NOT NULL,
    TOTAL_PRICE DOUBLE NOT NULL,
    USER_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (CART_ID)
);

-- create cart item table
CREATE TABLE IF NOT EXISTS CART_ITEM (
    CART_ITEM_ID VARCHAR(255) NOT NULL,
    PRICE DOUBLE NOT NULL,
    PRODUCT_ID VARCHAR(255),
    QUANTITY INTEGER NOT NULL,
    CART_ID VARCHAR(255),
    PRIMARY KEY (CART_ITEM_ID),
    CONSTRAINT CART_FK FOREIGN KEY (CART_ID) REFERENCES CART (CART_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

-- create order table
CREATE TABLE IF NOT EXISTS ORDER_TABLE (
    ORDER_ID VARCHAR(255) NOT NULL,
    TOTAL_ORDER_PRICE DOUBLE NOT NULL,
    USER_NAME VARCHAR(255) NOT NULL,
    BILLING_ADDRESS_ID VARCHAR(255),
    SHIPPING_ADDRESS_ID VARCHAR(255),
    PRIMARY KEY (ORDER_ID)
);

-- create order item table
CREATE TABLE IF NOT EXISTS ORDER_ITEM (
    ORDER_ITEM_ID VARCHAR(255) NOT NULL,
    ORDER_ITEM_PRICE DOUBLE NOT NULL,
    PRODUCT_ID VARCHAR(255) NOT NULL,
    QUANTITY INTEGER NOT NULL,
    ORDER_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (ORDER_ITEM_ID),
    CONSTRAINT ORDER_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDER_TABLE (ORDER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
