export const ADDRESS_ADD_REQUEST = 'ADDRESS_ADD_REQUEST';
export const ADDRESS_ADD_SUCCESS = 'ADDRESS_ADD_SUCCESS';
export const ADDRESS_ADD_FAIL = 'ADDRESS_ADD_FAIL';
export const ADDRESS_ADD_RESET = 'ADDRESS_ADD_RESET';

export const ADDRESS_LIST_MY_REQUEST = 'ADDRESS_LIST_MY_REQUEST';
export const ADDRESS_LIST_MY_SUCCESS = 'ADDRESS_LIST_MY_SUCCESS';
export const ADDRESS_LIST_MY_FAIL = 'ADDRESS_LIST_MY_FAIL';
export const ADDRESS_LIST_MY_RESET = 'ADDRESS_LIST_MY_RESET';

export const ADDRESS_DELETE_REQUEST = 'ADDRESS_DELETE_REQUEST';
export const ADDRESS_DELETE_SUCCESS = 'ADDRESS_DELETE_SUCCESS';
export const ADDRESS_DELETE_FAIL = 'ADDRESS_DELETE_FAIL';
export const ADDRESS_DELETE_RESET = 'ADDRESS_DELETE_RESET';
