export const CART_CLEAR_ITEMS = 'CART_RESET';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';

export const CART_DETAILS_REQUEST = 'CART_DETAILS_REQUEST';
export const CART_DETAILS_SUCCESS = 'CART_DETAILS_SUCCESS';
export const CART_DETAILS_FAIL = 'CART_DETAILS_FAIL';
export const CART_DETAILS_RESET = 'CART_DETAILS_RESET';

export const CART_ADD_ITEM_REQUEST = 'CART_ADD_ITEM_REQUEST';
export const CART_ADD_ITEM_SUCCESS = 'CART_ADD_ITEM_SUCCESS';
export const CART_ADD_ITEM_FAIL = 'CART_ADD_ITEM_FAIL';
export const CART_ADD_ITEM_RESET = 'CART_ADD_ITEM_RESET';

export const CART_REMOVE_ITEM_REQUEST = 'CART_REMOVE_ITEM_REQUEST';
export const CART_REMOVE_ITEM_SUCCESS = 'CART_REMOVE_ITEM_SUCCESS';
export const CART_REMOVE_ITEM_FAIL = 'CART_REMOVE_ITEM_FAIL';
export const CART_REMOVE_ITEM_RESET = 'CART_REMOVE_ITEM_RESET';
