export const PAYMENT_METHOD_ADD_REQUEST = 'PAYMENT_METHOD_ADD_REQUEST';
export const PAYMENT_METHOD_ADD_SUCCESS = 'PAYMENT_METHOD_ADD_SUCCESS';
export const PAYMENT_METHOD_ADD_FAIL = 'PAYMENT_METHOD_ADD_FAIL';
export const PAYMENT_METHOD_ADD_RESET = 'PAYMENT_METHOD_ADD_RESET';

export const PAYMENT_METHOD_LIST_MY_REQUEST = 'PAYMENT_METHOD_LIST_MY_REQUEST';
export const PAYMENT_METHOD_LIST_MY_SUCCESS = 'PAYMENT_METHOD_LIST_MY_SUCCESS';
export const PAYMENT_METHOD_LIST_MY_FAIL = 'PAYMENT_METHOD_LIST_MY_FAIL';
export const PAYMENT_METHOD_LIST_MY_RESET = 'PAYMENT_METHOD_LIST_MY_RESET';
